from dataclasses import dataclass
from typing import Protocol, runtime_checkable


@dataclass
class Change:
    host: str
    hash: str
    waiting: bool = False
    deleted: bool = False
    disabled: bool = False


@runtime_checkable
class AppContext(Protocol):
    changes: list[Change]
    status_msg: str
    default_host: str | None
    submitted_keys: set[tuple[str, str]]

    def toggle_waiting(self, row: int) -> None: ...
    def toggle_deleted(self, row: int) -> None: ...
    def toggle_disabled(self, row: int) -> None: ...
    def refresh_all(self) -> None: ...
    def open_change_webui(self, row: int) -> None: ...
    def set_automerge(self, row: int) -> None: ...
    def add_change(self, commit_hash: str, host: str) -> None: ...
    def delete_all_submitted(self) -> None: ...
    def purge_deleted(self) -> None: ...
    def restore_all(self) -> None: ...
    def quit(self) -> None: ...
